name: web-deploy-on-release
on:
  push:
    tags:
      - '*.*.*'
env:
  GODOT_VERSION: "4.0"
  RELEASE_NAME: beta13
  SUBDIR: beta13
  DEBIAN_FRONTEND: noninteractive
jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - name: Godot 4.0 Beta Download
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.0/beta13/Godot_v4.0-beta13_linux.x86_64.zip
          wget https://downloads.tuxfamily.org/godotengine/4.0/beta13/Godot_v4.0-beta13_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.${RELEASE_NAME}
          unzip Godot_v4.0-beta13_linux.x86_64.zip
          rm -f /usr/local/bin/godot
          mv Godot_v4.0-beta13_linux.x86_64 /usr/local/bin/godot
          unzip Godot_v4.0-beta13_export_templates.tpz
          mv templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.${RELEASE_NAME}
          rm -f Godot_v4.0-beta13_export_templates.tpz Godot_v4.0-beta13_linux.x86_64.zip
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          lfs: true
      - name: Web Build
        run: |
          mkdir -v -p Deploy/Web
          godot -v --export "Web" Deploy/Web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: Deploy/Web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: Deploy/Web # The folder the action should deploy.
